### ISSUE TITLE
Module command not working

### ISSUE THREAD

**Issue by ryanburgess** [ryanburgess/sassysass#18]
Since updating to Node.js 4.2.1 the module command isn't working. It's missing the module request.

$ sassysass module

module.js:340
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by ryanburgess** [comment]
The latest version of SassySass is now working as expected.
